### ISSUE TITLE
Disable all LoRAs on second pass

### ISSUE THREAD

**Issue by DavideAlidosi** [w-e-w/sd-webui-hires-fix-tweaks#4]
Hi again, would it be possible to add an option to remove all LoRAs from the second pass?
Thank you again.

**Comment by w-e-w** [comment]
yes it's possible and not even that hard
if you want to do it manually then just don't add have loras in hr promps
this can could be automated, I will consider this adding as a feature

**Comment by DavideAlidosi** [comment]
Thank you, I really appreciate the effort.

**Comment by w-e-w** [comment]
implemented
Add a checkbox that when check will remove extra networks from first pass prompt before creating hires prompt
Remove First Pass Extra Networks https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/2753923657b3f67e2f57bceb4e39d6f34048f11d
see [readme for useg](https://github.com/w-e-w/sd-webui-hires-fix-tweaks?tab=readme-ov-file#remove-first-pass-extra-networks)

**Comment by DavideAlidosi** [comment]
First of all, thank you very much for adding the feature as requested, I am very grateful!
Unfortunately, however, I am unable to get that feature to work, I have set the Hires prompt mode to Append and enabled the Remove First Pass Extra Networks flag, but there are no mofiches to the generated image.
I am currently on version 1.7.0 of WebUI.

**Comment by w-e-w** [comment]
pushed a fix https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/982c55a1b2330ddd95f618305535f99cc905abd0

**Comment by DavideAlidosi** [comment]
> pushed a fix [982c55a](https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/982c55a1b2330ddd95f618305535f99cc905abd0)

That's great, how can I offering you a beer?

**Comment by DavideAlidosi** [comment]
After further testing, I noticed that if LoRA is loaded via styles, the extension is unable to disable it at the hi-res fix level.
I think at this point it is related to how WebUI reads and applies the code between style and prompt.

**Comment by w-e-w** [comment]
this is to be expeted, and the behavior is also documented in readme

this is webui prompt pipeline
1 take user input `prompt` `hr prompt` `styles`
2. if `hr prompt` is blank then copy `prompt` to `hr prompt`
3. the same set of apply styles the `prompt` and `hr prompt`

this extentions `remove extra networks` and `hires prompt mode `happens between 1~2, and so will not touch Styles

---

it is possible to remove extra networks from styles, but this also ment that 

but it also introduce extra complications like
1. if this is applied to styles then should this be integrated with high ress prompt mode
2. for append and prepend, should it be added befor syles of after,
3. the the biggest issue is that it's operating under the assumption that Styles will not be modified and to be the same in prompt and hr prompt,
- becaus of this in the info text first pass `Prompt` includs the styles but `Hires prompt` dose not
- when extracting styles 

allow modifying Styles in Hires prompt I would basically need to implement a Style system of Hires pass
since I don't want to implement this (at least for now)

---

damn it, I think found a bug related to Styles with hires prompt

---

thanks for offering
I just never learning how to set up a donation page
if I do make one in the future I will probably put it on my profile
so I guess for now the best way you can help is just give me feedback (like what you did just now)

**Comment by DavideAlidosi** [comment]
Thank you very much for the comprehensive answer, very welcome.
Among the extensions I am using is [https://github.com/SirVeggie/extension-style-vars](https://github.com/SirVeggie/extension-style-vars) which among other things allows you to separate the contents of the prompt between first and second pass using the syntax `{first pass:second pass}`.
Again, this works at the prompt level, but maybe it can give you some pointers.
